### ISSUE TITLE
Cross platform Releases

### ISSUE THREAD

**Issue by omegaui** [HummyMolecula/Hummy-IDE#1]
@HummyMolecula 

This IDE is an electron app, so, it will be better to include release packages for **all platforms** to target **more users**.

Although the release page contains the **`.exe`** executable but the question arises does it supports 64 or 32 bit.

Second, the release page doesn't contains any linux executable i.e **`.AppImage`**.

Some linux systems cannot build from source without workarounds.

![Screenshot from 2022-02-10 11-00-11](https://user-images.githubusercontent.com/73544069/153343713-ee33bfca-94b7-473f-ad4e-35b8f9f3443f.png)

Just take an example of Ubuntu 20.04, Although it is an LTS release but the default node package version in launchpad is not up-to-date to build this IDE from source without suffering with some manual installations of packages.

Also, providing some **screenshots** will attract more users.
One cannot imagine the UI just by thinking.

**Comment by HummyMolecula** [comment]
Thank you!

**Comment by HummyMolecula** [comment]
Can you suggest how to do this? I'm on Windows, how can I build it for other platforms?

**Comment by omegaui** [comment]
@HummyMolecula 

Well, 
I am not a Web Guy, but, I think you can achieve this by Virtualizing other platforms on your system, using VirtualBox.
Or see if your package manager supports this.

**Comment by omegaui** [comment]
Also
Whenever you do a comment just include @username to send a notification.

**Comment by HummyMolecula** [comment]
@omegaui
Thank you!

**Comment by HummyMolecula** [comment]
Becouse i am programming on windows, with my package mager i can generate installion files only for windows and linux :/

**Comment by HummyMolecula** [comment]
So i cann`t generate files for macOS.
Can you help me? 🎈

**Comment by HummyMolecula** [comment]
Which OS you have?

**Comment by HummyMolecula** [comment]
https://github.com/HummyMolecula/Hummy-IDE/issues/1#issue-1129427971
I see, you tried compile my IDE? Thanks 😄

**Comment by omegaui** [comment]
> Which OS you have?

@HummyMolecula 

I have both Windows(10 21H1) and Linux(Ubuntu 20.04 and 21.04) on my side.

Since, I use the Java Platform so there is no need to own multiple platforms on my side as the `.jar` file runs independent of the platform.

So, even if I want I cannot help you with building macos builds. But....


You can use the `darling` emulation layer to emulate macos on your side or the Virtual Box.

**Comment by HummyMolecula** [comment]
@omegaui 
See my new release!
