### ISSUE TITLE
Redundant Dependencies

### ISSUE THREAD

**Issue by omegaui** [HummyMolecula/Hummy-IDE#5]
https://github.com/HummyMolecula/Hummy-IDE/blob/c59f63637e0a7c3eda6a8aa7cea7a0dd70988ae9/package-lock.json#L1-L100

Remove Redundant Dependencies ...

I see your `package` file contains dependencies that are pre-installed in default nodejs installations, there is no need to include them!

**Comment by HummyMolecula** [comment]
Note: I don't want to remove redundant dependencies in version branches, so I only removed them in master branch.
